CREATE TABLE [dbo].[Cart_Books]
(
	CartID UNIQUEIDENTIFIER NOT NULL,
	BookID INT NOT NULL,
	[Quantity] INT NOT NULL DEFAULT 1,
	[DateCreated] DATETIME NOT NULL DEFAULT GetDate(),
	[DateLastModified] DATETIME NOT NULL DEFAULT GetDate(),
	CONSTRAINT [PK_CartBook] PRIMARY KEY ([CartID], [BookID]),
	CONSTRAINT [FK_CartBook_Cart] FOREIGN KEY (CartID) REFERENCES Cart(ID),
	CONSTRAINT [FK_CartBook_Book] FOREIGN KEY (BookID) REFERENCES Books(BookID)
)
